### ISSUE TITLE
a

### ISSUE THREAD

**Issue by mahartariq** [ravi-prakash1907/Computer-Graphics#1]
a

**Comment by ravi-prakash1907** [comment]
Yes. Being more accurate:
> 1. Translate the triangle to the origin (by 1 unit back from both X and Y-axis)
> 2. Rotate it translated figure by desired angle (say 45°)  
> 3. Translate back the new triangle at the previous position by 1 unit forward from both X and Y-axis (to remove the effect of step 1 )  

It's actually one of the easiest way to translate object to origin for many other operations like shearing etc..
